name: Ruff Auto Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: ChartBoost Ruff-Action
      uses: chartboost/ruff-action@v1
      with:
        args: 'format --config ./pyproject.toml'
        src: './jacl'
    - name: Analysing the code with ruff
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Ruff: Auto-Style Fixes'
